### ISSUE TITLE
Unsatisfactory display of latex formula in EPUB exports.

### ISSUE THREAD

**Issue by luis-r-izquierdo** [pressbooks/pb-mathjax#101]
In some cases (see MWE below), it seems that the presence of a tag like `<h1></h1>` before a latex formula can mess up how the formula is displayed in the EPUB export.

To be specific, the following code is fine:
```$p &gt; 0$```

i.e., it displays in the EPUB as:
<img width="77" alt="Screenshot 2024-09-06 at 14 03 22" src="https://github.com/user-attachments/assets/ab883118-7149-4efa-b170-7da3f9b5de25">

But if I add an h1 element before the latex equation:
```
<h1>Exercises</h1>
$p &gt; 0$
```

then the formula does not display correctly in the EPUB:
<img width="448" alt="Screenshot 2024-09-06 at 14 02 22" src="https://github.com/user-attachments/assets/a6e5c37c-9046-40f9-9e35-05e0f431d25b">

I do not think this is a  WP QuickLaTeX issue, because if I deactivate the plug in, and I code the following:
```
<h1>Exercises</h1>
[latex]p &gt; 0[/latex]
```
I get the following unsatisfactory display in the EPUB:
<img width="430" alt="Screenshot 2024-09-06 at 14 11 00" src="https://github.com/user-attachments/assets/c38280db-fdc7-4c50-aca0-5bbbff511a3a">

This resembles a lot the following bug in the PDF exports: https://github.com/pressbooks/pb-mathjax/issues/21 
Cheers
Luis

**Comment by arzola** [comment]
This will be solved with #103 and https://github.com/pressbooks/pressbooks/pull/3925

**Comment by SteelWagstaff** [comment]
@luis-r-izquierdo we released a new version of this repo with lots of improvements in March. This should resolve the issue (and give you some new tools for LaTeX). See https://pressbooks.community/t/improved-support-for-mathematical-scientific-notation/4156/4 for more details and let us know if this issue (or similar ones) persist for you!

**Comment by luis-r-izquierdo** [comment]
Thanks so much @SteelWagstaff !!! I just tried on my book (hosted at [https://wisc.pb.unizin.org/](https://wisc.pb.unizin.org/)) and the errors are still there, but I guess I have to wait a little bit until they update it. 
Thanks so much!

**Comment by luis-r-izquierdo** [comment]
Hi @SteelWagstaff, unfortunately the problem still persists in my book :( , even though it is using version 6.23.2 of Pressbooks. You can download the EPUB I just generated at https://wisc.pb.unizin.org/agent-based-evolutionary-game-dynamics/ and search for "QuickLaTeX.com" :(. Thanks for your help!

**Comment by arzola** [comment]
@luis-r-izquierdo probably this could be related to quicklatex integration, we fixed this on standalone pb-mathjax solution, we would take a look on our quicklatex behaviour

**Comment by SteelWagstaff** [comment]
hi @luis-r-izquierdo I think @arzola is right -- it appears that you're using the WP QuickLaTeX plugin in your book. The fixes and improvements we made are for our native LaTeX/MathJax solution. You can test what happens in your book by deactivating this plugin (https://wisc.pb.unizin.org/agent-based-evolutionary-game-dynamics/wp-admin/plugins.php). I took a look at your book settings and it looks like you should be able to make that migration without extra effort and it will 'just work'. If you notice any weird issues after deactivating, you can always reactivate and we can investigate further.

**Comment by SteelWagstaff** [comment]
@luis-r-izquierdo there are two ways of rendering LaTeX in Pressbooks -- a native solution controlled by this repo, and an alternative solution that uses the WP QuickLaTeX plugin. Only one can be operating in a book at a given time. We made recent improvements to make the native solution better so that fewer people would need to resort to the third-party plugin. See https://guide.pressbooks.com/chapter/add-mathematical-notation/ and https://pressbooks.community/t/improved-support-for-mathematical-scientific-notation/4156 for more details. When we were getting started with your book all those years ago, I think the third party plugin might have been the only option. I'd recommend deactivating the plugin to see if the native solution solves your problem. Two other positives -- you can use standard LaTeX delimiters by default (instead of having to use [latex] shortcodes) and the expressions will be rendered in the webbook using MathJax instead of creating images. Should be a much better & more acessible reading experience.

**Comment by luis-r-izquierdo** [comment]
Thank you so much for all your help @arzola and @SteelWagstaff. 
My (particular) problem now is that I have intensively used `$...$` as in-line math delimiter in my book. I understand that I would have to replace all these with `\(...\)`. 
I'll think about how much effort it will take me to manually replace all these delimiters and make a decision.  
Thanks a lot Guys!
Luis

**Comment by SteelWagstaff** [comment]
Makes sense -- FYI this is a feature we're planning to add support for soon: https://github.com/pressbooks/pb-mathjax/issues/124. Maybe you want to wait until this is enabled in the native solution?

**Comment by luis-r-izquierdo** [comment]
I definitely want to wait for that!! Thank you so much, as always, @SteelWagstaff !!!
