### ISSUE TITLE
MathML is always displaying on a new line, can't be used inline

### ISSUE THREAD

**Issue by beckej13820** [pressbooks/pb-mathjax#19]
Playing with the new MathML coverage, I can't get MathML to display inline. It always creates a line break. 

Asking on the forums, it appears Abby Elder is having the same problems, and Steel actually replicated it in his webbook when he cut and paste a source with MathML. Line breaks are being added before and after every MathML equation.

<img width="929" alt="Screen Shot 2019-07-23 at 9 02 22 PM" src="https://user-images.githubusercontent.com/29982981/61757201-9ac35f80-ad8d-11e9-9121-d6ed669cb202.png">

https://integrations.pressbooks.network/testbookfun/chapter/three-popular-data-displays/

**Comment by dac514** [comment]
Test case:

```html
<p class="para block" id="fwk-shafer-ch02_s01_s03_p01">In our example of the exam scores in a statistics class, five students scored in the 80s. The number 5 is the <em class="emphasis">frequency</em> of the group labeled “80s.” Since there are 30 students in the entire statistics class, the proportion who scored in the 80s is 5/30. The number 5/30, which could also be expressed as <span class="inlineequation" id="shafer-20121106-125753-084206"><math xml:id="fwk-shafer-ch02-m0003" display="inline"><mn>0.1</mn><mrow><mover accent="true"><mn>6</mn><mo stretchy="true">-</mo></mover></mrow><mo>≈</mo><mo>.</mo><mn>1667</mn></math></span>, or as 16.67%, is the <span class="margin_term"><a class="glossterm">relative frequency</a><span class="glossdef">Of a class of measurements, the proportion of all measurements in the data set that are in the class.</span></span> of the group labeled “80s.” Every group (the 70s, the 80s, and so on) has a relative frequency. We can thus construct a diagram by drawing for each group, or class, a vertical bar whose length is the relative frequency of that group. For example, the bar for the 80s will have length 5/30 unit, not 5 units. The diagram is a <span class="margin_term"><a class="glossterm">relative frequency histogram</a><span class="glossdef">A graphical device showing how data are distributed across the range of their values by collecting them into classes and indicating the proportion of measurements in each class.</span></span> for the data, and is shown in <a class="xref" href="#fwk-shafer-ch02_s01_s03_f01">Figure 2.4 "Relative Frequency Histogram"</a>. It is exactly the same as the frequency histogram except that the vertical axis in the relative frequency histogram is not frequency but relative frequency.</p>
```

In webbook, turns into:

```html
<p class="para block" id="fwk-shafer-ch02_s01_s03_p01">In our example of the exam scores in a statistics class, five students scored in the 80s. The number 5 is the <em class="emphasis">frequency</em> of the group labeled “80s.” Since there are 30 students in the entire statistics class, the proportion who scored in the 80s is 5/30. The number 5/30, which could also be expressed as <span class="inlineequation" id="shafer-20121106-125753-084206"></p>
<math xml:id="fwk-shafer-ch02-m0003" ... snip ...
```

Specifically:

`</p><math`

**Comment by dac514** [comment]
It’s a WordPress bug:

https://core.trac.wordpress.org/ticket/13340

If I apply this patch it fixes the issue:

https://core.trac.wordpress.org/attachment/ticket/13340/13340.diff

For obvious reasons, I can’t simply patch wp-includes/formatting.php, WordPress must do it…

**Comment by dac514** [comment]
Left a Trac comment:

https://core.trac.wordpress.org/ticket/13340#comment:15

**Comment by SteelWagstaff** [comment]
Confirmed fixed with upstream WordPress changes. See example here: https://integrations.pressbooks.network/test-clone/chapter/math-test-latex/

**Comment by beckej13820** [comment]
Steel, 

I'm not sure this should be closed. In your example, the mathml is not being displayed inline. The pythagorean theorem in the MathML section is still getting line breaks before nad after it.

![Image](https://github.com/user-attachments/assets/558c8b3f-b6c0-4bea-bcd7-4e2d5bd7c722)
